// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createNotebook: (prepMode: PrepMode) => typedError<Notebook, AppError>(__TAURI_INVOKE("create_notebook", { prepMode })),
	listNotebooks: () => typedError<Notebook[], AppError>(__TAURI_INVOKE("list_notebooks")),
	listDocuments: (notebookId: string) => typedError<Document[], AppError>(__TAURI_INVOKE("list_documents", { notebookId })),
	/**
	 *  Kick off ingestion for `path` into `notebook_id`. Returns the new document
	 *  id immediately; the frontend listens on `document-status` events for
	 *  progress and terminal state.
	 */
	ingestDocument: (notebookId: string, path: string) => typedError<string, AppError>(__TAURI_INVOKE("ingest_document", { notebookId, path })),
};

/* Types */
export type AppError = { kind: "Db"; message: string } | { kind: "Keychain"; message: string } | { kind: "Migration"; message: string } | { kind: "NotFound" } | { kind: "InvalidInput"; message: string } | { kind: "Io"; message: string } | { kind: "Internal"; message: string };

// Emphasis for flashcards, guide tone, and worked-example selection.
export type DifficultyFocus = "conceptual" | "problem_solving" | "memorization" | "mixed";

/**
 *  A single source attached to a notebook (PDF, URL, markdown, raw text).
 *  `local_path` is always populated — even URL/text sources materialise a
 *  file under the app-managed folder so downstream parsing is uniform.
 */
export type Document = {
	id: string,
	notebook_id: string,
	filename: string,
	source_type: SourceType,
	source_url: string | null,
	local_path: string,
	page_count: number | null,
	status: DocumentStatus,
	error: string | null,
	created_at: number,
};

/**
 *  Lifecycle of a document inside the ingestion pipeline. Rendered verbatim
 *  in the UI as a parse-state badge (see docs/design.md §6.3).
 */
export type DocumentStatus = "pending" | "parsing" | "embedding" | "ready" | "failed";

/**
 *  Which exam the notebook is preparing for. Drives prompt selection across
 *  every generation feature (chat, study guide, flashcards, podcast).
 */
export type ExamType = "internal" | "midsem" | "endsem" | "viva" | "practical" | "assignment" | "competitive" | "custom";

// Question/answer shape the student will face in the exam.
export type Format = "mcq" | "short" | "long" | "oral" | "numerical" | "mixed";

/**
 *  A persisted notebook row. `id` is a uuid v4 and `created_at` is unix
 *  epoch seconds.
 */
export type Notebook = {
	id: string,
	title: string,
	created_at: number,
	exam_type: ExamType,
	format: Format,
	subject: string | null,
	duration_minutes: number | null,
	exam_at: number | null,
	difficulty_focus: DifficultyFocus | null,
};

/**
 *  All six prep-mode fields supplied when a notebook is created. Snapshotted
 *  onto every generated artifact so regenerations stay consistent with the
 *  student's original intent.
 */
export type PrepMode = {
	// Which exam the student is preparing for.
	exam_type: ExamType,
	// Question format of that exam.
	format: Format,
	// Free-text subject label (e.g. "Thermodynamics", "Constitutional Law").
	subject: string | null,
	// Minutes the exam itself will take.
	duration_minutes: number | null,
	// Unix epoch seconds of when the exam starts; null means unspecified.
	exam_at: number | null,
	// Tone and emphasis of generated output.
	difficulty_focus: DifficultyFocus | null,
};

/**
 *  Where a document originally came from. MVP ships `pdf`; the other variants
 *  are reserved for Phase 1 / P2 follow-ups (URL import, markdown paste, raw
 *  text drop).
 */
export type SourceType = "pdf" | "url" | "md" | "text";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

