// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createNotebook: (prepMode: PrepMode) => typedError<Notebook, AppError>(__TAURI_INVOKE("create_notebook", { prepMode })),
	listNotebooks: () => typedError<Notebook[], AppError>(__TAURI_INVOKE("list_notebooks")),
	listDocuments: (notebookId: string) => typedError<Document[], AppError>(__TAURI_INVOKE("list_documents", { notebookId })),
	/**
	 *  Kick off ingestion for `path` into `notebook_id`. Returns the new document
	 *  id immediately; the frontend listens on `document-status` events for
	 *  progress and terminal state.
	 */
	ingestDocument: (notebookId: string, path: string) => typedError<string, AppError>(__TAURI_INVOKE("ingest_document", { notebookId, path })),
	listProviders: () => typedError<ProviderInfo[], AppError>(__TAURI_INVOKE("list_providers")),
	/**
	 *  Validate a candidate key against the live provider before persisting it.
	 *  Returns the same status enum used everywhere else so the UI can render
	 *  uniform feedback (Connected, InvalidKey, Unreachable, Error).
	 */
	validateProviderKey: (provider: ProviderId, apiKey: string) => typedError<ProviderStatus, AppError>(__TAURI_INVOKE("validate_provider_key", { provider, apiKey })),
	/**
	 *  Probe the provider with the key currently stored in the keychain.
	 *  Returns `NotConfigured` when no key is stored (and the provider needs
	 *  one); for Ollama it always pings since it has no key requirement.
	 */
	getProviderStatus: (provider: ProviderId) => typedError<ProviderStatus, AppError>(__TAURI_INVOKE("get_provider_status", { provider })),
	storeProviderKey: (provider: ProviderId, apiKey: string) => typedError<null, AppError>(__TAURI_INVOKE("store_provider_key", { provider, apiKey })),
	deleteProviderKey: (provider: ProviderId) => typedError<null, AppError>(__TAURI_INVOKE("delete_provider_key", { provider })),
	setActiveProvider: (provider: "anthropic" | "openai" | "google" | "openrouter" | "ollama" | null) => typedError<null, AppError>(__TAURI_INVOKE("set_active_provider", { provider })),
	getActiveProvider: () => typedError<"anthropic" | "openai" | "google" | "openrouter" | "ollama" | null, AppError>(__TAURI_INVOKE("get_active_provider")),
};

/* Types */
export type AppError = { kind: "Db"; message: string } | { kind: "Keychain"; message: string } | { kind: "Migration"; message: string } | { kind: "NotFound" } | { kind: "InvalidInput"; message: string } | { kind: "Io"; message: string } | { kind: "Internal"; message: string };

// Emphasis for flashcards, guide tone, and worked-example selection.
export type DifficultyFocus = "conceptual" | "problem_solving" | "memorization" | "mixed";

/**
 *  A single source attached to a notebook (PDF, URL, markdown, raw text).
 *  `local_path` is always populated — even URL/text sources materialise a
 *  file under the app-managed folder so downstream parsing is uniform.
 */
export type Document = {
	id: string,
	notebook_id: string,
	filename: string,
	source_type: SourceType,
	source_url: string | null,
	local_path: string,
	page_count: number | null,
	status: DocumentStatus,
	error: string | null,
	created_at: number,
};

/**
 *  Lifecycle of a document inside the ingestion pipeline. Rendered verbatim
 *  in the UI as a parse-state badge (see docs/design.md §6.3).
 */
export type DocumentStatus = "pending" | "parsing" | "embedding" | "ready" | "failed";

/**
 *  Which exam the notebook is preparing for. Drives prompt selection across
 *  every generation feature (chat, study guide, flashcards, podcast).
 */
export type ExamType = "internal" | "midsem" | "endsem" | "viva" | "practical" | "assignment" | "competitive" | "custom";

// Question/answer shape the student will face in the exam.
export type Format = "mcq" | "short" | "long" | "oral" | "numerical" | "mixed";

/**
 *  A single model exposed by a provider. `id` is the provider-native
 *  identifier passed back into chat requests; `label` is the friendly name
 *  for UI; `context_window` is in tokens when known.
 */
export type ModelInfo = {
	id: string,
	label: string,
	context_window: number | null,
};

/**
 *  A persisted notebook row. `id` is a uuid v4 and `created_at` is unix
 *  epoch seconds.
 */
export type Notebook = {
	id: string,
	title: string,
	created_at: number,
	exam_type: ExamType,
	format: Format,
	subject: string | null,
	duration_minutes: number | null,
	exam_at: number | null,
	difficulty_focus: DifficultyFocus | null,
};

/**
 *  All six prep-mode fields supplied when a notebook is created. Snapshotted
 *  onto every generated artifact so regenerations stay consistent with the
 *  student's original intent.
 */
export type PrepMode = {
	// Which exam the student is preparing for.
	exam_type: ExamType,
	// Question format of that exam.
	format: Format,
	// Free-text subject label (e.g. "Thermodynamics", "Constitutional Law").
	subject: string | null,
	// Minutes the exam itself will take.
	duration_minutes: number | null,
	// Unix epoch seconds of when the exam starts; null means unspecified.
	exam_at: number | null,
	// Tone and emphasis of generated output.
	difficulty_focus: DifficultyFocus | null,
};

/**
 *  The five providers StudyLM can target. The serialized identifier is
 *  snake_case, matching the rest of the IPC surface and the keychain keys.
 */
export type ProviderId = "anthropic" | "openai" | "google" | "openrouter" | "ollama";

/**
 *  Provider summary for the Settings → Providers list. Exists so the
 *  frontend can render the picker without instantiating provider clients.
 */
export type ProviderInfo = {
	id: ProviderId,
	label: string,
	needs_api_key: boolean,
};

/**
 *  What `ping()` reports back to the UI. Status colors and copy in the
 *  Settings → Providers screen are driven off this.
 */
export type ProviderStatus = 
// No key configured (or for Ollama, the daemon was not probed yet).
{ kind: "NotConfigured" } | 
// Provider responded successfully to a low-cost ping.
{ kind: "Connected"; detail: {
	models: ModelInfo[],
} } | 
// Network reached the provider but it rejected our credentials.
{ kind: "InvalidKey"; detail: {
	message: string,
} } | 
/**
 *  We could not reach the provider at all (network down, Ollama not
 *  running, DNS failure, etc.).
 */
{ kind: "Unreachable"; detail: {
	message: string,
} } | 
// Anything else that doesn't fit the above (5xx, malformed payload).
{ kind: "Error"; detail: {
	message: string,
} };

/**
 *  Where a document originally came from. MVP ships `pdf`; the other variants
 *  are reserved for Phase 1 / P2 follow-ups (URL import, markdown paste, raw
 *  text drop).
 */
export type SourceType = "pdf" | "url" | "md" | "text";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

